name: firefox

on:
  pull_request:
  push:
    branches:
    - main
    
jobs:
  might:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      options: --user 1001
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn
      - name: Build Flcss
        run: yarn build
      - name: Run Tests
        run: yarn might --firefox
      - name: Upload Errors
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: might.error.*.*