name: unit-tests

on:
  pull_request:
  push:
    branches:
    - main
    
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn ci
      - name: Run Tests
        run: yarn jest --collect-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true